### ISSUE TITLE
repeating events

### ISSUE THREAD

**Issue by 150d** [WLAN-Kabel/ioBroker.calendar#27]
Hi,

I noticed that repeating events are not shown/imported into ioBroker by the adapter. If you have e.g. a monthly meeting, it will only be shown once (the first instance of the series.)

Could the adapter show the recurring events of the series as well?

Regards

**Comment by WLAN-Kabel** [comment]
I am already working on the implementation for CalDAV. If you use the calendars via the Google API, that should already work.
