### ISSUE TITLE
1.2.0: VCalendarError: <constructor> <parse> Cannot read property '0' of null

### ISSUE THREAD

**Issue by agross** [WLAN-Kabel/ioBroker.calendar#34]
**Describe the bug**  

After updating to 1.2.0 with the fix for #29 this error is logged:

```
(12493) VCalendarError: <constructor> <parse> Cannot read property '0' of null
    at new VCalendar (/opt/iobroker/node_modules/iobroker.calendar/lib/vcalendar.js:54:19)
    at Calendar.getCaldavCalendarEvents (/opt/iobroker/node_modules/iobroker.calendar/main.js:534:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The log also says `Updated calendar "TRS"`, but the calendar's objects are empty.

**To Reproduce**  

See #29 

**Expected behavior**  

See #29 

**Versions:**  
 See #29

**Comment by agross** [comment]
After reviewing the `VCalendar` code, what is the reason for parsing the calendar yourself? There are libs like [node-ical](https://www.npmjs.com/package/node-ical) that will handle this for you.

**Comment by agross** [comment]
I tested this lib with the Google Calendar that throws the error reported above. It was able to parse the ICS file without issues.

**Comment by WLAN-Kabel** [comment]
Hey, I know the library, but the library cannot create iCal and I don't want to use two libraries for reading and writing.

Could you maybe download the file and send it to me? Then I could check where the error occurs.

Email: wlan-kabel@outlook.de

**Comment by agross** [comment]
>  I don't want to use two libraries for reading and writing.

As far as I can tell package.json currently does not include any library to read or write calendar entries.

Do you really want to run into all the bugs that other battle-tested libraries ran into, like this one?

> Could you maybe download the file and send it to me?

This is my private calendar, I'm not going to send it to you.

> Then I could check where the error occurs.

The error occurs here:

```
{
    "tzid": {
        "params": null,
        "values": "Etc/UTC"
    },
    "xLicLocation": {
        "params": null,
        "values": "Etc/UTC"
    },
    "standard": [
        {
            "tzoffsetfrom": {
                "params": null,
                "values": "+0000"
            },
            "tzoffsetto": {
                "params": null,
                "values": "+0000"
            },
            "tzname": {
                "params": null,
                "values": "GMT"
            },
            "dtstart": {
                "params": null,
                "values": "19700101T000000"
            }
        }
    ]
}
(node:99703) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of null
    at new VTimezone (/Users/agross/Downloads/ioBroker.calendar/lib/vtimezone.js:15:25)
    at VCalendar.parse (/Users/agross/Downloads/ioBroker.calendar/lib/vcalendar.js:76:33)
    at new VCalendar (/Users/agross/Downloads/ioBroker.calendar/lib/vcalendar.js:52:18)
    at data.then.v (/Users/agross/Downloads/ioBroker.calendar/test.js:5:16)
```

The object above the stack trace is the one that is passed [here](https://github.com/WLAN-Kabel/ioBroker.calendar/blob/383def1fa4aea34c7e0f542ee78d1d6f9c1d1072/lib/vcalendar.js#L75).

Why did you wrap methods in a try/catch block? Catching the exception and only logging the error *message* (instead of the full stack trace) makes it harder than necessary to find the exact line that the error occurred in. The ioBroker logfile itself doesn't show the full stack trace (see OP) and `VCalendarError: <constructor> <parse> Cannot read property '0' of null` implies the problem lies in `VCalendar`, when it actually occurs in `VTimezone`.

**Comment by agross** [comment]
Now this one (after installing from GH):

```
(9516) TypeError: this.dtend.getDate is not a function at new VEvent (/opt/iobroker/node_modules/iobroker.calendar/lib/vevent.js:91:43) at VCalendar.parse (/opt/iobroker/node_modules/iobroker.
```
