### ISSUE TITLE
Baikal CalDAV not working

### ISSUE THREAD

**Issue by haegar33** [WLAN-Kabel/ioBroker.calendar#46]
**Describe the bug**  
Calendars for a Baikal CalDAV users are not loaded. Adapter Objects stay empty

**To Reproduce**  
1. Installed ioBroker.calendar version 1.2.0
2. Providing CalDAV URL, Username ("helge") and Password
3. Save and restart adapter

**Screenshots & Logfiles**  
`calendar.0	2020-10-29 10:29:27.506	debug	(14450) Schedules started`
`calendar.0	2020-10-29 10:29:27.505	error	(14450) [401] null`
`calendar.0	2020-10-29 10:29:27.305	debug	(14450) http://192.168.178.23/baikal/html/cal.php/principals/`
`calendar.0	2020-10-29 10:29:27.078	debug	(14450) Read calendar of ''`
`calendar.0	2020-10-29 10:29:27.049	error	(14450) [401] null`
`calendar.0	2020-10-29 10:29:26.845	debug	(14450) http://192.168.178.23/baikal/html/cal.php/principals/`

`calendar.0	2020-10-29 10:29:26.506	info	(14450) starting. Version 1.2.0 in /opt/iobroker/node_modules/iobroker.calendar, node: v10.23.0, js-controller: 3.1.6`

**Versions:**  
 - Adapter version: 1..0 
 - JS-Controller version: 3.1.6
 - Node version: 10.23.0
 - Operating system: Raspbian Lite
- Baikal on NAS: V0.4.6

**Additional context** 
The path for my Baikal php scripts is /baikal/html/

URLs tried:

 http://192.168.178.23/baikal/html/cal.php/principals
 http://192.168.178.23/baikal/html/cal.php/principals/helge
http://192.168.178.23/baikal/html/cal.php/calendars/helge/
http://192.168.178.23/baikal/html/dav.php/principals/

Reading the principal parameters with wget from the console provides correct answers, i.e. a describtive html file like:

> Properties

>d:principal-collection-set	/baikal/html/cal.php/principals/
>d:current-user-principal	/baikal/html/cal.php/principals/helge/
>d:current-user-privilege-set	d:read, d:read-acl, d:read-current-user-privilege-set
>d:acl	
>Principal	Privilege	
>d:authenticated	d:read	(protected)
>d:owner	/
>d:supported-report-set	d:expand-property, d:principal-property-search, d:principal-search-property-set
>d:resourcetype	d:collection
>Generated by SabreDAV 3.1.3 (c)2007-2015 http://sabre.io/

**Comment by haegar33** [comment]
Actually while trying to solve the problem I changed the Baikal authentication setting from DIgest to Basic. After that the calendars were imported. If not the case, this setting should be noted in the documentation.

**Comment by maxblome** [comment]
Thanks for the feedback. I will include this in the manual.

Can you also tell me the correct base URL so I can add it to the list?
